apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: strimzi
    chart: strimzi-kafka-operator-0.46.0
    component: service-account
    heritage: Helm
    release: strimzi-kafka-operator
  name: strimzi-cluster-operator
  namespace: kafka
