---
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: IfNotPresent

- op: add
  path: /spec/template/metadata/labels/app
  value: argocd-redis
  
- op: add
  path: /spec/template/metadata/labels/project
  value: argocd
