#kustomization:render
namespace: kube-system
helmCharts:
- name: sealed-secrets
  namespace: kube-system
  repo: https://bitnami-labs.github.io/sealed-secrets
  releaseName: sealed-secrets
  version: "2.17.2"
  valuesFile: values.yaml
  includeCRDs: true