apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: redpanda-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v2.4.2
    helm.sh/chart: operator-v2.4.2
  name: redpanda-controller-operator
  namespace: redpanda-operator
