apiVersion: v1
data:
  controller_manager_config.yaml: |-
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    health:
      healthProbeBindAddress: :8081
    kind: ControllerManagerConfig
    leaderElection:
      leaderElect: true
      resourceName: aa9fc693.vectorized.io
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: redpanda-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v2.4.2
    helm.sh/chart: operator-v2.4.2
  name: redpanda-controller-operator-config
  namespace: redpanda-operator
