apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: redpanda-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v2.4.2
    helm.sh/chart: operator-v2.4.2
  name: redpanda-controller-operator-metrics-service
  namespace: redpanda-operator
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/instance: redpanda-controller
    app.kubernetes.io/name: operator
