apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: redpanda-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v2.4.2
    helm.sh/chart: operator-v2.4.2
  name: redpanda-controller-operator-compat
  namespace: redpanda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redpanda-controller-operator-compat
subjects:
- kind: ServiceAccount
  name: redpanda-controller-operator
  namespace: redpanda-operator
