---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: data-connect-cluster
  labels:
    app: data-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
  namespace: kafka
spec:
  version: 4.0.0
  replicas: 1
  bootstrapServers: redpanda-demo-0.redpanda-demo.redpanda-operator.svc.cluster.local.:9092
  build:
    output:
      type: docker
      image: riupie/kafka-connect:latest
      pushSecret: registry-auth-dockerconfig-secret
      additionalKanikoOptions: 
        - --verbosity=info
    plugins:
      - name: camel-postgresql-sink-kafka-connector
        artifacts:
          - type: maven
            group: org.apache.camel.kafkaconnector
            artifact: camel-postgresql-sink-kafka-connector
            version: 4.11.0
  template:
    pod:
      imagePullSecrets:
        - name: registry-auth-dockerconfig-secret 
  logging:
    type: inline
    loggers:
      kafka.root.logger.level: "INFO"
  resources:
    requests:
      cpu: 200m
      memory: 2Gi
    limits:
      memory: 2Gi
  jvmOptions:
    -Xms: 2g
    -Xmx: 2g
  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  config:
    group.id: data-connect
    offset.storage.topic: data-connect-offsets
    config.storage.topic: data-connect-configs
    status.storage.topic: data-connect-status
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: env
    config.providers.env.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider