apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redpanda-console-httproute
  namespace: redpanda-operator
spec:
  parentRefs:
  - name: internal-lab-gateway
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - 'redpanda-console.lab.riupie.com'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: redpanda-demo-console
          namespace: redpanda-operator
          port: 8080