#kustomization:render
helmCharts:
- name: gateway-helm
  repo: oci://registry-1.docker.io/envoyproxy
  namespace: envoy-gateway-system
  releaseName: eg
  version: "1.3.2"
  valuesFile: values.yaml
  includeCRDs: true