---
labels:
  - pairs:
      env: development
resources:
  - ../../../base/external-dns/default
  - external-dns-bind9-tsig-key.yaml

patches:
  - path: patches/external-dns-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: external-dns