- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --domain-filter=lab.riupie.com

- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: EXTERNAL_DNS_RFC2136_HOST
      value: 192.168.10.9
    - name: EXTERNAL_DNS_RFC2136_PORT
      value: "53"
    - name: EXTERNAL_DNS_RFC2136_ZONE
      value: lab.riupie.com
    - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
      value: "true"
    - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
      value: externaldns-key
    - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
      value: hmac-sha512
    - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
      valueFrom:
        secretKeyRef:
          key: ddns-key
          name: external-dns-bind9-tsig-key