apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: internal-http-filter-redirect
  namespace: envoy-gateway-system
spec:
  parentRefs:
  - name: internal-lab-gateway
    namespace: envoy-gateway-system
    sectionName: http
  hostnames:
  - '*.lab.riupie.com'
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301