---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: rahmataw96@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-privkey
    solvers:
      - selector:
          dnsZones:
            - "riupie.com"
        dns01:
          cloudflare:
            email: rahmataw96@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key