apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: games-httproute
  namespace: games
spec:
  parentRefs:
  - name: lab-gateway
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - 'games.riupie.com'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: service-2048
          namespace: games
          port: 80