apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/part-of: sealed-secrets
    app.kubernetes.io/version: 0.29.0
    helm.sh/chart: sealed-secrets-2.17.2
  name: sealed-secrets-controller-metrics
  namespace: kube-system
spec:
  ports:
  - name: metrics
    nodePort: null
    port: 8081
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/name: sealed-secrets
  type: ClusterIP
