apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.3.2
    helm.sh/chart: gateway-helm-1.3.2
  name: eg-gateway-helm-infra-manager
  namespace: envoy-gateway-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eg-gateway-helm-infra-manager
subjects:
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system
