apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.3.2
    control-plane: envoy-gateway
    helm.sh/chart: gateway-helm-1.3.2
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  ports:
  - name: grpc
    port: 18000
    targetPort: 18000
  - name: ratelimit
    port: 18001
    targetPort: 18001
  - name: wasm
    port: 18002
    targetPort: 18002
  - name: metrics
    port: 19001
    targetPort: 19001
  selector:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/name: gateway-helm
    control-plane: envoy-gateway
