apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.3.2
    helm.sh/chart: gateway-helm-1.3.2
  name: envoy-gateway
  namespace: envoy-gateway-system
