---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  timeout.reconciliation: "60s"
  application.instanceLabelKey: argocd.argoproj.io/instance
  url: https://argocd.lab.riupie.com
  kustomize.buildOptions: --enable-helm
  #dex.config: |
  #  connectors:
  #  - config:
  #      issuer: https://accounts.google.com
  #      clientID: $argocd-oidc-credential-secret:clientId
  #      clientSecret: $argocd-oidc-credential-secret:clientSecret
  #    type: oidc
  #    id: google
  #    name: Google

  # FIX ISSUE: https://github.com/argoproj/argo-cd/discussions/7936#discussioncomment-2267954
  resource.customizations.health.autoscaling_HorizontalPodAutoscaler: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "ScalingActive" and condition.reason == "FailedGetResourceMetric" then
              hs.status = "Progressing"
              hs.message = condition.message
              return hs
          end
          if condition.status == "True" then
              hs.status = "Healthy"
              hs.message = condition.message
              return hs
          end
        end
      end
      hs.status = "Healthy"
      return hs
    end
    hs.status = "Progressing"
    return hs