---
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: IfNotPresent

- op: add
  path: /spec/template/metadata/labels/app
  value: argocd-repo-server

- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 512Mi