---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: "[email]"
  policy.default: role:engineer
  policy.csv: |
    p, role:engineer, applications, get, */*, allow
    p, role:engineer, applications, action/apps/Deployment/restart, */*, allow
    p, role:engineer, applications, action/argoproj.io/Rollout/restart, */*, allow
    p, role:engineer, applications, delete, app/*, allow
    p, role:engineer, repositories, get, *, allow
    
    g, admin@riupie.com, role:admin