apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda-demo
  namespace: redpanda-operator
spec:
  chartRef:
    useFlux: false
  clusterSpec:
    config:
      connect:
        enabled: true
        clusters:
          - name: data-connect-cluster
            address: data-connect-cluster-connect-api.kafka.svc.cluster.local:8083
    tls:
      enabled: false
    external:
      domain: lab.riupie.com
    statefulset:
      replicas: 1
      initContainers:
        setDataDirOwnership:
          enabled: true