apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda-demo
  namespace: redpanda-operator
spec:
  chartRef:
    useFlux: false
  clusterSpec:
    connectors:
      enabled: true
      deployment:
        create: false
      connectors:
        bootstrapServers: "redpanda-demo-0.redpanda-demo.redpanda.svc.cluster.local.:9093"
    tls:
      enabled: false
    external:
      domain: lab.riupie.com
    statefulset:
      replicas: 1
      initContainers:
        setDataDirOwnership:
          enabled: true